name: Check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: DeterminateSystems/determinate-nix-action@c70cb8ae92d68c66953db28a26a63db1665bc837 # v3
      - name: Check formatting
        run: nix fmt -- --check
      - name: Check flake evaluation
        run: |
          nix eval .#nixosConfigurations.nixstation.config.system.build.toplevel.drvPath --no-write-lock-file
          nix eval .#nixosConfigurations.wslstation.config.system.build.toplevel.drvPath --no-write-lock-file
          nix eval .#nixosConfigurations.homestation.config.system.build.toplevel.drvPath --no-write-lock-file
          nix eval .#darwinConfigurations.macstation.system --apply 's: s.drvPath' --no-write-lock-file
